/*
 * Copyright (c) 2026 Bixbit - Krzysztof Benedyczak All rights reserved.
 * See LICENCE.txt file for licensing information.
 */
package pl.edu.icm.unity.store.migration.to4_5;

import org.apache.logging.log4j.Logger;
import org.springframework.stereotype.Component;

import pl.edu.icm.unity.base.group.GroupMembership;
import pl.edu.icm.unity.base.utils.Log;
import pl.edu.icm.unity.store.api.AttributesCachePendingDAO;
import pl.edu.icm.unity.store.api.MembershipDAO;
import pl.edu.icm.unity.store.migration.InDBContentsUpdater;

/**
 * Marks the attributes cache of every existing (entity, group) membership as pending, so that it gets
 * (re)generated by the standard background mechanism after the upgrade.
 */
@Component
class InDBUpdateFromSchema23 implements InDBContentsUpdater
{
	private static final Logger log = Log.getLogger(Log.U_SERVER_DB, InDBUpdateFromSchema23.class);

	private final MembershipDAO membershipDAO;
	private final AttributesCachePendingDAO pendingDAO;

	InDBUpdateFromSchema23(MembershipDAO membershipDAO, AttributesCachePendingDAO pendingDAO)
	{
		this.membershipDAO = membershipDAO;
		this.pendingDAO = pendingDAO;
	}

	@Override
	public int getUpdatedVersion()
	{
		return 23;
	}

	@Override
	public void update()
	{
		for (GroupMembership membership : membershipDAO.getAll())
			pendingDAO.markPending(membership.getEntityId(), membership.getGroup());
		log.info("Marked attributes cache as pending for all existing group memberships");
	}
}
