#######################################
# Credential definitions
#######################################

unityServer.core.credentials.1.credentialName=Certificate credential
unityServer.core.credentials.1.credentialType=certificate
unityServer.core.credentials.1.credentialDescription=Certificate credential.
unityServer.core.credentials.1.credentialConfigurationFile=${CONF}/samples/empty

#######################################
# Credential requirement definitions
#######################################

unityServer.core.credentialRequirements.1.credentialReqName=Password requirement
unityServer.core.credentialRequirements.1.credentialReqDescription=Password requirement.
unityServer.core.credentialRequirements.1.credentialReqContents.1=sys:password

unityServer.core.credentialRequirements.2.credentialReqName=Certificate requirement
unityServer.core.credentialRequirements.2.credentialReqDescription=Certificate requirement.
unityServer.core.credentialRequirements.2.credentialReqContents.1=Certificate credential

