# This configuration module enables SAML IdP feature. Authentication is configured for local Unity users.


unityServer.core.endpoints.samlWebIdp.endpointType=SAMLWebIdP
unityServer.core.endpoints.samlWebIdp.endpointConfigurationFile=${CONF}/modules/saml/saml-webidp.properties
unityServer.core.endpoints.samlWebIdp.contextPath=/saml-idp
unityServer.core.endpoints.samlWebIdp.endpointRealm=defaultRealm
unityServer.core.endpoints.samlWebIdp.endpointName=UNITY SAML web authentication
unityServer.core.endpoints.samlWebIdp.endpointAuthenticators=pwd;cert

unityServer.core.endpoints.samlSOAPIdp.endpointType=SAMLSoapIdP
unityServer.core.endpoints.samlSOAPIdp.endpointConfigurationFile=${CONF}/modules/saml/saml-webidp.properties
unityServer.core.endpoints.samlSOAPIdp.contextPath=/soapidp
unityServer.core.endpoints.samlSOAPIdp.endpointRealm=defaultRealm
unityServer.core.endpoints.samlSOAPIdp.endpointName=UNITY SOAP SAML service
unityServer.core.endpoints.samlSOAPIdp.endpointAuthenticators=pwd
