/*
 * Copyright (c) 2014 ICM Uniwersytet Warszawski All rights reserved.
 * See LICENCE.txt file for licensing information.
 */
package pl.edu.icm.unity.saml.metadata;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import xmlbeans.org.oasis.saml2.metadata.EntityDescriptorDocument;

/**
 * A very simple servlet: returns SAML metadata generated by a given {@link MetadataProvider}.
 * 
 * @author K. Benedyczak
 */
public class MetadataServlet extends HttpServlet
{
	private MetadataProvider metaProvider;
	
	public MetadataServlet(MetadataProvider metaProvider)
	{
		this.metaProvider = metaProvider;
	}
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException
	{
		resp.setContentType("application/samlmetadata+xml");
		EntityDescriptorDocument meta = metaProvider.getMetadata();
		PrintWriter writer = resp.getWriter();
		writer.write(meta.xmlText());
		writer.flush();
	}
}
