#!/bin/bash

. /etc/unity-idm/startup.properties


if [ -e "$PID" ]
 then
  if [ -d /proc/$(cat "$PID") ]
   then
     echo "A UNITY instance may be already running with process id "$(cat $PID)
     echo "If this is not the case, delete the file $PID and re-run this script"
     exit 1
   fi
fi

cd /

CP=.$(find "$LIB" -name '*.jar' -exec printf ":{}" \;)

export CLASSPATH=$CP

RUN_COMMAND="$JAVA ${MEM} ${OPTS} ${DEFS} pl.edu.icm.unity.server.UnityApplication ${PARAM}"
if [ "${AUTHBIND}" ]
then
        nohup "${AUTHBIND}" --deep ${RUN_COMMAND} >& "$STARTLOG" &
else
        nohup ${RUN_COMMAND} >& "$STARTLOG" &
fi

echo $! > "$PID"