/*
 * Copyright (c) 2013 ICM Uniwersytet Warszawski All rights reserved.
 * See LICENCE.txt file for licensing information.
 */
package pl.edu.icm.unity.webadmin.tprofile.dryrun;

import pl.edu.icm.unity.server.utils.UnityMessageSource;
import pl.edu.icm.unity.webui.common.safehtml.HtmlLabel;

import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

/**
 * UI Component used by DryRun - {@link IntroStep}.
 * 
 * @author Roman Krysinski
 */
public class IntroStepComponent extends CustomComponent 
{
	private UnityMessageSource msg;
	private VerticalLayout mainLayout;
	private HtmlLabel introLabel;
	private static final long serialVersionUID = 6976972617938388430L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param msg 
	 */
	public IntroStepComponent(UnityMessageSource msg) 
	{
		this.msg = msg;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		introLabel.setHtmlValue("DryRun.IntroStepComponent.introLabel");
	}

	private VerticalLayout buildMainLayout() {
		mainLayout = new VerticalLayout();
		mainLayout.setSizeFull();
		mainLayout.setMargin(true);
		
		setSizeFull();
		
		introLabel = new HtmlLabel(msg);
		introLabel.setSizeFull();
		mainLayout.addComponent(introLabel);
		
		return mainLayout;
	}

}
