// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package pl.edu.icm.unity.engine.builders;

import pl.edu.icm.unity.confirmations.ConfirmationConfiguration;

public class ConfirmationConfigurationBuilder extends
		ConfirmationConfigurationBuilderBase<ConfirmationConfigurationBuilder>
{
	public static ConfirmationConfigurationBuilder confirmationConfiguration()
	{
		return new ConfirmationConfigurationBuilder();
	}

	public ConfirmationConfigurationBuilder()
	{
		super(new ConfirmationConfiguration());
	}

	public ConfirmationConfiguration build()
	{
		return getInstance();
	}
}

class ConfirmationConfigurationBuilderBase<GeneratorT extends ConfirmationConfigurationBuilderBase<GeneratorT>>
{
	private ConfirmationConfiguration instance;

	protected ConfirmationConfigurationBuilderBase(ConfirmationConfiguration aInstance)
	{
		instance = aInstance;
	}

	protected ConfirmationConfiguration getInstance()
	{
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMsgTemplate(String aValue)
	{
		instance.setMsgTemplate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNotificationChannel(String aValue)
	{
		instance.setNotificationChannel(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNameToConfirm(String aValue)
	{
		instance.setNameToConfirm(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTypeToConfirm(String aValue)
	{
		instance.setTypeToConfirm(aValue);

		return (GeneratorT) this;
	}
}
