/*
 * Copyright (c) 2013 ICM Uniwersytet Warszawski All rights reserved.
 * See LICENCE.txt file for licensing information.
 */
package pl.edu.icm.unity.engine.builders;

import pl.edu.icm.unity.types.basic.NotificationChannel;

/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */
public class NotificationChannelBuilder extends NotificationChannelBuilderBase<NotificationChannelBuilder> {
    public static NotificationChannelBuilder notificationChannel() {
        return new NotificationChannelBuilder();
    }

    public NotificationChannelBuilder() {
        super(new NotificationChannel());
    }

    public NotificationChannel build() {
        return getInstance();
    }
}

class NotificationChannelBuilderBase<GeneratorT extends NotificationChannelBuilderBase<GeneratorT>> {
    private NotificationChannel instance;

    protected NotificationChannelBuilderBase(NotificationChannel aInstance) {
        instance = aInstance;
    }

    protected NotificationChannel getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withConfiguration(String aValue) {
        instance.setConfiguration(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withFacilityId(String aValue) {
        instance.setFacilityId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue) {
        instance.setName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withDescription(String aValue) {
        instance.setDescription(aValue);

        return (GeneratorT) this;
    }
}
