/*
 * Copyright (c) 2013 ICM Uniwersytet Warszawski All rights reserved.
 * See LICENCE.txt file for licensing information.
 */
package pl.edu.icm.unity.webadmin.tprofile.wizard;

import pl.edu.icm.unity.server.authn.remote.RemotelyAuthenticatedInput;
import pl.edu.icm.unity.server.utils.UnityMessageSource;
import pl.edu.icm.unity.webadmin.tprofile.incubator.StickyComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

/**
 * UI Component used by {@link ProfileStep}.
 * 
 * @author Roman Krysinski
 */
public class ProfileStepComponent extends CustomComponent 
{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private StickyComponent stickyComponent_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param msg 
	 */
	public ProfileStepComponent(UnityMessageSource msg) 
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void handle(RemotelyAuthenticatedInput authnInput) 
	{

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// stickyComponent_1
		stickyComponent_1 = new StickyComponent();
		stickyComponent_1.setImmediate(false);
		stickyComponent_1.setWidth("100.0%");
		stickyComponent_1.setHeight("100.0%");
		mainLayout.addComponent(stickyComponent_1);
		mainLayout.setExpandRatio(stickyComponent_1, 1.0f);
		
		return mainLayout;
	}
}
