/*
 * Copyright (c) 2013 ICM Uniwersytet Warszawski All rights reserved.
 * See LICENCE.txt file for licensing information.
 */
package pl.edu.icm.unity.webadmin.tprofile.wizard;

import org.vaadin.teemu.wizards.Wizard;

import pl.edu.icm.unity.server.utils.UnityMessageSource;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

/**
 * Component that displays the wizard - used in {@link WizardDialog}.
 * 
 * @author Roman Krysinski
 */
public class WizardDialogComponent extends CustomComponent 
{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 3574810301425807584L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Wizard wizard;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public WizardDialogComponent(UnityMessageSource msg) 
	{
		buildMainLayout();
		setCompositionRoot(mainLayout);

		wizard.addStep(new IntroStep(msg));
		wizard.addStep(new SandboxStep(msg));
		wizard.addStep(new ProfileStep(msg));
		wizard.addStep(new DryRunStep(msg));
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() 
	{
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// wizard
		wizard = new Wizard();
		wizard.setImmediate(false);
		wizard.setWidth("100.0%");
		wizard.setHeight("100.0%");
		mainLayout.addComponent(wizard);
		
		return mainLayout;
	}

}
