/*
 * Copyright (c) 2020 Bixbit - Krzysztof Benedyczak All rights reserved.
 * See LICENCE.txt file for licensing information.
 */
package pl.edu.icm.unity.types.basic;

import java.util.Arrays;
import java.util.Base64;
import java.util.Random;

/**
 * Randomly generated byte array, uniquely identifying user.
 *
 * @author R. Ledzinski
 */
public class UserHandle
{
	final byte[] value;

	public UserHandle(final byte[] value)
	{
		this.value = copyArray(value);
	}

	private UserHandle()
	{
		this.value = new byte[64];
		new Random().nextBytes(value);
	}

	public static UserHandle fromString(final String stringValue)
	{
		return new UserHandle(Base64.getDecoder().decode(stringValue));
	}

	public String asString()
	{
		return Base64.getEncoder().encodeToString(value);
	}

	public byte[] getBytes()
	{
		return copyArray(value);
	}

	public static UserHandle create()
	{
		return new UserHandle();
	}

	private byte[] copyArray(final byte[] value)
	{
		return Arrays.copyOf(value, value.length);
	}
}
